baseURL = "https://kiwislice.github.io/coursera-html-css-javascript-test/"
languageCode = "en-us"
title = "Html/Css/Js學習筆記"
themesDir = "themes"
theme = "hugo-theme-docdock"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[[menu.main]]
    name = "Home"
    url = "https://kiwislice.github.io/coursera-html-css-javascript-test/"
    weight = 1

[[menu.main]]
    name = "Docs"
    url = "https://kiwislice.github.io/coursera-html-css-javascript-test/docs/"
    weight = 2

[params]
  google_analytics_id=""
  homepage_button_link = 'https://kiwislice.github.io/coursera-html-css-javascript-test/docs'
  homepage_button_text = 'Read The Docs'
  homepage_intro = 'Whisper is a documentation theme built with Hugo. The design and functionality is intentionally minimal.'
  #homepage_image = '/images/terminal.gif'

  [params.homepage_meta_tags]
    meta_description = "Hugo Whisper is a documentation theme built with Hugo."
    meta_og_title = "Html/Css/Js學習筆記"
    meta_og_type = "website"
    meta_og_url = "https://hugo-whisper.netlify.com"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-whisper-theme/master/images/tn.png"
    meta_og_description = "Hugo Whisper is a documentation theme built with Hugo."
    meta_twitter_card = "summary"
    meta_twitter_site = "@zerostaticio"
    meta_twitter_creator = "@zerostaticio"